/* oauth-twitter.vapi generated by valac 0.14.0, do not modify. */

[CCode (cheader_filename = "oauth-twitter.h")]
public class OauthTwitter {
	public OauthTwitter ();
	public Soup.Message Auth (string method, string url);
	public void getAccessToken_A ();
	public Gee.Map<string,string> getAccessToken_B (string pin);
	public void init (string token, string token_secret);
}
