/* oauth-twitter.h generated by valac 0.14.0, the Vala compiler, do not modify */


#ifndef __OAUTH_TWITTER_H__
#define __OAUTH_TWITTER_H__

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gee.h>
#include <libsoup/soup.h>

G_BEGIN_DECLS


#define TYPE_OAUTH_TWITTER (oauth_twitter_get_type ())
#define OAUTH_TWITTER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_OAUTH_TWITTER, OauthTwitter))
#define OAUTH_TWITTER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_OAUTH_TWITTER, OauthTwitterClass))
#define IS_OAUTH_TWITTER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_OAUTH_TWITTER))
#define IS_OAUTH_TWITTER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_OAUTH_TWITTER))
#define OAUTH_TWITTER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_OAUTH_TWITTER, OauthTwitterClass))

typedef struct _OauthTwitter OauthTwitter;
typedef struct _OauthTwitterClass OauthTwitterClass;
typedef struct _OauthTwitterPrivate OauthTwitterPrivate;

struct _OauthTwitter {
	GTypeInstance parent_instance;
	volatile int ref_count;
	OauthTwitterPrivate * priv;
};

struct _OauthTwitterClass {
	GTypeClass parent_class;
	void (*finalize) (OauthTwitter *self);
};


gpointer oauth_twitter_ref (gpointer instance);
void oauth_twitter_unref (gpointer instance);
GParamSpec* param_spec_oauth_twitter (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_oauth_twitter (GValue* value, gpointer v_object);
void value_take_oauth_twitter (GValue* value, gpointer v_object);
gpointer value_get_oauth_twitter (const GValue* value);
GType oauth_twitter_get_type (void) G_GNUC_CONST;
OauthTwitter* oauth_twitter_new (void);
OauthTwitter* oauth_twitter_construct (GType object_type);
void oauth_twitter_init (OauthTwitter* self, const gchar* token, const gchar* token_secret);
void oauth_twitter_getAccessToken_A (OauthTwitter* self);
GeeMap* oauth_twitter_getAccessToken_B (OauthTwitter* self, const gchar* pin);
SoupMessage* oauth_twitter_Auth (OauthTwitter* self, const gchar* method, const gchar* url);


G_END_DECLS

#endif
