/* twitter.vapi generated by valac 0.14.0, do not modify. */

[CCode (cheader_filename = "twitter.h")]
public class Twitter {
	public Twitter ();
	public void getAccessToken_A ();
	public Gee.Map<string,string> getAccessToken_B (string pin);
	public Json.Parser home_timeline ();
	public void init (string token, string token_secret);
}
