/* twitter.h generated by valac 0.14.0, the Vala compiler, do not modify */


#ifndef __TWITTER_H__
#define __TWITTER_H__

#include <glib.h>
#include <oauth-twitter.h>
#include <json-glib/json-glib.h>

G_BEGIN_DECLS



JsonParser* twitter_home_timeline (OauthTwitter* ot);


G_END_DECLS

#endif
